using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    public partial class AddLeagueMemberAndLeagueFields : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS nba_leagues (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" text NOT NULL,
                    "Description" text NOT NULL DEFAULT '',
                    "CreatedByUserId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
                    "InviteCode" text,
                    "IsPublic" boolean NOT NULL DEFAULT FALSE,
                    CONSTRAINT "PK_nba_leagues" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                ALTER TABLE nba_leagues ADD COLUMN IF NOT EXISTS "CreatedByUserId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
                ALTER TABLE nba_leagues ADD COLUMN IF NOT EXISTS "InviteCode" text;
                ALTER TABLE nba_leagues ADD COLUMN IF NOT EXISTS "IsPublic" boolean NOT NULL DEFAULT FALSE;
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "LeagueMembers" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "LeagueId" integer NOT NULL,
                    "UserId" uuid NOT NULL,
                    "Role" text NOT NULL,
                    "JoinedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_LeagueMembers" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_LeagueMembers_nba_leagues_LeagueId" FOREIGN KEY ("LeagueId") REFERENCES nba_leagues ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_LeagueMembers_profiles_UserId" FOREIGN KEY ("UserId") REFERENCES profiles (id) ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_nba_leagues_CreatedByUserId" ON nba_leagues ("CreatedByUserId");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_LeagueMembers_LeagueId_UserId" ON "LeagueMembers" ("LeagueId", "UserId");
                CREATE INDEX IF NOT EXISTS "IX_LeagueMembers_UserId" ON "LeagueMembers" ("UserId");
                """);

            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_nba_leagues_profiles_CreatedByUserId'
                    ) THEN
                        ALTER TABLE nba_leagues ADD CONSTRAINT "FK_nba_leagues_profiles_CreatedByUserId"
                            FOREIGN KEY ("CreatedByUserId") REFERENCES profiles (id) ON DELETE RESTRICT;
                    END IF;
                END $$;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "LeagueMembers");
            migrationBuilder.DropTable(name: "nba_leagues");
        }
    }
}
